MESSAGE ("Loaded: Generic-gcc-hcs12.cmake")

IF (NOT DEFINED HC12_CORE)
	SET (HC12_CORE HCS12)
ENDIF()

SET (CMAKE_EXECUTABLE_SUFFIX                        ".elf")

SET (CMAKE_C_FLAGS_INIT                             "-mshort -ffixed-z -m68hcs12 -fomit-frame-pointer")
SET (CMAKE_C_FLAGS_DEBUG_INIT 						"-g")
SET (CMAKE_C_FLAGS_MINSIZEREL_INIT 					"-Os")
SET (CMAKE_C_FLAGS_RELEASE_INIT 					"-Os")
SET (CMAKE_C_FLAGS_RELWITHDEBINFO_INIT 				"-g -Os")
SET (CMAKE_C_STANDARD_LIBRARIES_INIT   				"")

SET(CMAKE_C_LINK_EXECUTABLE "<CMAKE_C_COMPILER> <FLAGS> <CMAKE_C_LINK_FLAGS> <LINK_FLAGS> <OBJECTS> -o <TARGET> -Wl,-Map,<TARGET_BASE>.map <LINK_LIBRARIES>")
